apiVersion: appsody.dev/v1alpha1
kind: AppsodyApplication
metadata:
  name: example-appsodyapplication
spec:
  # Add fields here
  applicationImage: frankji/liberty-ltf
  stack: java-microprofile
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /
      port: 9080
    initialDelaySeconds: 60
    periodSeconds: 5
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /
      port: 9080
    initialDelaySeconds: 30
    periodSeconds: 5
